const actions = {
  GETCLIENTS: 'GETCLIENTS',
  GETCLIENTSSUCCESS: 'GETCLIENTSSUCCESS',
  CREATECLIENTSTYPES: 'CREATECLIENTSTYPES',
  DELETECLIENTSTYPES: 'DELETECLIENTSTYPES',
  UPDATECLIENTSTYPES: 'UPDATECLIENTSTYPES',
}

export default actions;
