const actions = {
  GETBRANCHES: 'GETBRANCHES',
  GETBRANCHESSSUCESS: 'GETBRANCHESSSUCESS',
  CREATEBRANCHES: 'CREATEBRANCHES',
  UPDATEBRANCHES: 'UPDATEBRANCHES',
  DELETEBRANCHES: 'DELETEBRANCHES',
  GETEXPENSESECTIONS: 'GETEXPENSESECTIONS',
  GETEXPENSESECTIONSSUCCESS: 'GETEXPENSESECTIONSSUCCESS',
  CREATEEXPENSESECTIONS: 'CREATEEXPENSESECTIONS',
  UPDATEEXPENSESECTIONS: 'UPDATEEXPENSESECTIONS',
  DELETEEXPENSESECTIONS: 'DELETEEXPENSESECTIONS'
}

export default actions;
