const actions = {
  GETBRANCHES: 'GETBRANCHES',
  GETBRANCHESSSUCESS: 'GETBRANCHESSSUCESS',
  CREATEBRANCHES: 'CREATEBRANCHES',
  UPDATEBRANCHES: 'UPDATEBRANCHES',
  DELETEBRANCHES: 'DELETEBRANCHES'
}

export default actions;
