const actions = {
  GETBRANCHES: 'GETBRANCHES',
  GETBRANCHESSSUCESS: 'GETBRANCHESSSUCESS',
  CREATEBRANCHES: 'CREATEBRANCHES',
  UPDATEBRANCHES: 'UPDATEBRANCHES',
  DELETEBRANCHES: 'DELETEBRANCHES',
  GETEXPENSESECTIONS: 'GETEXPENSESECTIONS',
  GETEXPENSESECTIONSSUCCESS: 'GETEXPENSESECTIONSSUCCESS',
  CREATEEXPENSESECTIONS: 'CREATEEXPENSESECTIONS',
  UPDATEEXPENSESECTIONS: 'UPDATEEXPENSESECTIONS',
  DELETEEXPENSESECTIONS: 'DELETEEXPENSESECTIONS',
  GETPAYMENTS: 'GETPAYMENTS',
  GETPAYMENTSSUCESS: 'GETPAYMENTSSUCESS',
  CREATEPAYMENTS: 'CREATEPAYMENTS',
  UPDATEPAYMENTS: 'UPDATEPAYMENTS',
  DELETEPAYMENTS: 'DELETEPAYMENTS',
}

export default actions;
