const actions = {
  GETCREATELAWSUITES: 'GETCREATELAWSUITES',
  GETCREATELAWSUITESSUCESS: 'GETCREATELAWSUITESSUCESS',
  CREATELAWSUITES: 'CREATELAWSUITES',
  GETPAPERS: 'GETPAPERS',
  GETPAPERSSUCCESS: 'GETPAPERSSUCCESS'
}

export default actions;
