const actions = {
  GETCREATELAWSUITES: 'GETCREATELAWSUITES',
  GETCREATELAWSUITESSUCESS: 'GETCREATELAWSUITESSUCESS',
  CREATELAWSUITES: 'CREATELAWSUITES',
  GETPAPERS: 'GETPAPERS',
  GETPAPERSSUCCESS: 'GETPAPERSSUCCESS',
  GETALLLAWSUITES: 'GETALLLAWSUITES',
  GETALLLAWSUITESSUCCESS: 'GETALLLAWSUITESSUCCESS'
}

export default actions;
