const actions = {
  GETCREATELAWSUITES: 'GETCREATELAWSUITES',
  GETCREATELAWSUITESSUCESS: 'GETCREATELAWSUITESSUCESS',
  CREATELAWSUITES: 'CREATELAWSUITES',
  GETPAPERS: 'GETPAPERS',
  GETPAPERSSUCCESS: 'GETPAPERSSUCCESS',
  GETALLLAWSUITES: 'GETALLLAWSUITES',
  GETALLLAWSUITESSUCCESS: 'GETALLLAWSUITESSUCCESS',
  GETCASETYPES: 'GETCASETYPES',
  GETCASETYPESSUCCESS: 'GETCASETYPESSUCCESS',
  CREATECASETYPES: 'CREATECASETYPES',
  UPDATECASETYPES: 'UPDATECASETYPES',
  DELETECASETYPES: 'DELETECASETYPES'
}

export default actions;
