const actions = {
  GETUSERS: 'GETUSERS',
  GETUSER: 'GETUSER',
  GETUSERSSUCCESS: 'GETUSERSSUCCESS',
  CREATEUSER: 'CREATEUSER',
  SHOWUSER: 'SHOWUSER',
  SHOWUSERSUCCESS: 'SHOWUSERSUCCESS',
  UPDATEUSER: 'UPDATEUSER',
  DELETEUSER: 'DELETEUSER'
}

export default actions;
